### ISSUE TITLE
Regular file system hot reloading is not working

### ISSUE THREAD

**Issue by johanhelsing** [johanhelsing/bevy_web_asset#1]
It's happening because the filesystem watcher implementation in bevy tries to downcast the asset io to FileAssetIO. Since we're wrapping it, that downcast fails, and nothing happens.

Bevy issue: https://github.com/bevyengine/bevy/issues/1414

**Comment by johanhelsing** [comment]
This should be possible to fix now :)

But not sure when I'll get the time to do it. If anyone wants to give it a go, check the linked bevy issue above for details!

**Comment by voidentente** [comment]
This should probably be closed @johanhelsing

**Comment by johanhelsing** [comment]
Yes, thanks :)
