### ISSUE TITLE
Going forward with Bevy 0.12

### ISSUE THREAD

**Issue by voidentente** [johanhelsing/bevy_web_asset#17]
Bevy 0.12 adds native support for remote asset sources, making most code here redundant.
Will `bevy_web_asset` become a legacy crate, or will it provide boilerplate implementations for http/https?

```
app.register_asset_source("http", ..);
app.register_asset_source("https", ..);
```

**Comment by johanhelsing** [comment]
I haven't looked into asset sources in bevy 0.12, but if it's more than just a line or two, or a bevy feature, i'd like the crate to continue to exist.

A PR would be welcome ;)

**Comment by voidentente** [comment]
Looking into a PR, expect one this week

**Comment by johanhelsing** [comment]
0.7.0 is out! Thanks for reviving this crate :D
