### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by oli-obk** [johanhelsing/bevy_web_asset#22]
isahc is not easily usable on android, because it always uses openssl and doesn't have a published version that can opt-out of that (https://github.com/sagebind/isahc/issues/199).

I read https://github.com/johanhelsing/bevy_web_asset/pull/18#issuecomment-1819126299, but it's not clear to me why isahc was preferred over surf, when both appear to not have the issue with loading some urls.

I can do the work and switch back to surf (and set it up so it works with rustls) if that is ok with y'all

**Comment by johanhelsing** [comment]
I'm ok with that. I think they're both unmaintained, which is unfortunate, but i also prefer surf.
