### ISSUE TITLE
Support for Bevy ^0.14

### ISSUE THREAD

**Issue by NEON725** [johanhelsing/bevy_web_asset#29]
More details about the update here: https://bevyengine.org/news/bevy-0-14/

Logging this issue as a formality. I have not performed a technical investigation in to how this update affects bevy_web_asset.

**Comment by johanhelsing** [comment]
A PR would be very welcome (unless this is now built into vevy? I also haven't read the release post yet)

**Comment by NEON725** [comment]
Ha. I just forked to try and update this, but someone else beat me to it.

Seems to be resolved by https://github.com/johanhelsing/bevy_web_asset/pull/30

**Comment by NEON725** [comment]
Reopening because 0.9 is not yet available on https://crates.io/crates/bevy_web_asset

**Comment by NEON725** [comment]
Further investigation: Although the README.md was updated, that PR did not bump the version: https://github.com/johanhelsing/bevy_web_asset/blob/main/Cargo.toml#L15

This *may* have borked the official 0.8 release, since the 0.8 version seems to now include the changes to support bevy ^0.14, in contrast to the documentation.

**Comment by NEON725** [comment]
Good news! Nothing was uploaded to crates.io in response to the merge, so that version is not clobbered after all. Just need to bump the version and merge again, then make the 0.9 version publicly available.

**Comment by NEON725** [comment]
Aside from the versioning issues, it seems to be working in my simple test setup when I add to my bevy ^0.14 project via the git checkout URL.

**Comment by johanhelsing** [comment]
I do releases with `cargo-release`, so `Cargo.toml` version is bumped automatically when I release. I simply haven't been back at my computer to release since I merged that PR.

New version is out now, thanks for the heads up!
