### ISSUE TITLE
IoTaskPool resource not found in browser

### ISSUE THREAD

**Issue by gilescope** [johanhelsing/bevy_web_asset#3]
Got: panicked at 'IoTaskPool resource not found'.

Anyone seen this error before? I'm on bevy 0.7 at the moment (waiting a bit longer to upgrade to 0.8).

Is there some additional setup to do for wasm given things are a tad different on the browser?

**Comment by johanhelsing** [comment]
Adding the plugin used to be slightly more finicky. See the 0.3.0 readme: https://github.com/johanhelsing/bevy_web_asset/tree/v0.3.0

**Comment by gilescope** [comment]
Thanks - that got me further: no `AssetLoader` found for the following extension: jpeg?raw=true
Unfortunately I'm trying to point at urls on github for now. Maybe I can register that as another jpeg extension???

**Comment by johanhelsing** [comment]
Yeah, seems it's getting confused by the query arg.

Perhaps it's possible to hack your way around it by adding bogus query args that ends in .jpeg?

like this:

```rust
asset_server.load("https://github.com/someimage.jpeg?raw=true&bogusextensionhack=.jpg"),
```
