### ISSUE TITLE
ocasional panic

### ISSUE THREAD

**Issue by gilescope** [johanhelsing/bevy_web_asset#4]
The unwrap here is causing a panic occasionally:
https://github.com/johanhelsing/bevy_web_asset/blob/d4cd4f42f255c39db9f79434c283259e2313d74f/src/web_asset_io.rs#L26

```
panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(TypeError: NetworkError when attempting to fetch resource.
)', /home/gilescope/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_web_asset-0.4.0/src/web_asset_io.rs:26:83
```

**Comment by johanhelsing** [comment]
Thanks. I guess warning and retrying after a small timeout is probably the best thing to do in most cases?

We could do that as first measure, then add special casing for various http 4xx and 5xx codes later.

**Comment by gilescope** [comment]
Sounds perfect! I guess it depends on the status code as to if it’s
sensible to retry.

**Comment by johanhelsing** [comment]
I fixed the panic at least. Don't have time to look into retrying now, but created new issues for that.
